### ISSUE TITLE
Protoc install process

### ISSUE THREAD

**Issue by TheWizardTower** [golemcloud/docs#34]
So, the golem docs mention that you need version 15+, then say "just use brew."

For those of us who aren't on Mac, we're sent to the protoc website, which has a helpful script to install it.

Unfortunately, it grabs version 3.14.

So, having a look at those scripts, then modifying them to grab a newer version, and having them in the docs would be enormously helpful.

**Comment by vigoo** [comment]
Good point, and I should go through the whole docs and check the steps on my Linux machine when I get home. Previously only added specifics for OSX because that's much easier (not having to cover an infinite amount of different distros)

**Comment by TheWizardTower** [comment]
For sure. The process was made harder because I was running Gentoo, which is *well* outside the normal range of distros. :)

**Comment by vigoo** [comment]
We are having precompiled CLI binaries since 1.0, and we will also get rid of the protobuf dependency for building CLI from source for 1.2, so I don't hink we should put more effort in documenting the protoc install process.
